export const BANK_LIST = [
  { name: "KEB하나은행", code: "081" },
  { name: "SC제일은행", code: "023" },
  { name: "국민은행", code: "004" },
  { name: "신한은행", code: "088" },
  { name: "외환은행", code: "005" },
  { name: "우리은행", code: "020" },
  { name: "한국시티은행", code: "027" },
  { name: "경남은행", code: "039" },
  { name: "광주은행", code: "034" },
  { name: "대구은행", code: "031" },
  { name: "부산은행", code: "032" },
  { name: "전북은행", code: "037" },
  { name: "제주은행", code: "035" },
  { name: "기업은행", code: "003" },
  { name: "농협", code: "011" },
  { name: "수협", code: "007" },
  { name: "한국산업은행", code: "002" },
  { name: "한국수출입은행", code: "008" },
  { name: "우리종합금융", code: "295" },
  { name: "SBI저축은행", code: "103" },
  { name: "애큐온저축은행(HK)", code: "104" },
  { name: "키움YES저축은행(키움증권)", code: "264" },
  { name: "푸른저축은행(상호저축은행)", code: "050" },
];
